name: "Helm Deployment"

on:
  # push:
  #   branches: 
  #     - azure-migration
  # pull_request:
  #   branches:
  #     - azure-migration
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  helm-deploy:
    name: "Helm Deployment"
    runs-on: ubuntu-lastest

    defaults:
      run:
        shell: bash
        working-directory: ./
    
    steps:
      
      # Checkout to Github actions runner
      - name: Action Runner Checkout
        uses: actions/checkout@v4

      # Install lastest version of Helm
      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0 
        with:
          version: latest

      # Install the lastest version of Terrarform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} 

      # Initialize the Working Environment
      - name: Terraform Init
        # uses: hashicorp/setup-terraform@v3
        run: terraform init

      # Validate all Terraform Files
      - name: Terraform Validate
        run: terraform validate

      # Plan the install Cilium via helm.tf
      - name: Terraform Plan
        uses: hashicorp/setup-terraform@v3
        continue-on-error: true
        with:
          tf_actions_subcommand: 'plan'
          args: '-target=helm.tf -out=helmtf'   

      # Install Cilium via helm.tf
      - name: Terraform Apply
        uses: hashicorp/setup-terraform@v3
        with:
          tf_actions_subcommand: 'apply'
          args: 'helmtf'

      # Destroy the Environment
      - name: Terraform Destroy
        run: terraform destroy


    
